export const START_MODAL = 'START_MODAL';
export const END_MODAL = 'END_MODAL';
export const RESET_MODAL = 'RESET_MODAL';
export const START_LOADING_MODAL_DATA = 'START_LOADING_MODAL_DATA';
export const END_LOADING_MODAL_DATA = 'END_LOADING_MODAL_DATA';
