export const ENTER_SEARCH_MENU = 'ENTER_SEARCH_MENU';
export const EXIT_SEARCH_MENU = 'EXIT_SEARCH_MENU';

export const START_LOADING_NOTES = 'START_LOADING_NOTES_SEARCH_MENU';
export const END_LOADING_NOTES = 'END_LOADING_NOTES_SEARCH_MENU';

export const START_LOADING_COLLECTIONS = 'START_LOADING_COLLECTIONS_SEARCH_MENU';
export const END_LOADING_COLLECTIONS = 'END_LOADING_COLLECTIONS_SEARCH_MENU';

export const LOAD_NOTES = 'LOAD_NOTES_SEARCH_MENU';
export const LOAD_COLLECTIONS = 'LOAD_COLLECTIONS_SEARCH_MENU';

export const ADD_NOTE = 'ADD_NOTE_SEARCH_MENU';
export const REMOVE_NOTE = 'REMOVE_NOTE_SEARCH_MENU';

export const RESET_ALL = 'RESET_ALL_SEARCH_MENU';

export const LOAD_NOTES_TO_DELETE = 'LOAD_NOTE_TO_DELETE';
export const LOAD_COLLECTIONS_TO_DELETE = 'LOAD_COLLECTIONS_TO_DELETE';
