// Notes Menu
export const ENTER_CREATE_NOTE = "ENTER_CRETE_NOTE";
export const CLOSE_CREATE_NOTE = "CLOSE_CREATE_NOTE";
export const NOTES_MENU_LOAD = "NOTES_MENU_LOAD";
export const NOTES_MENU_ENTER_VIEW = "NOTES_MENU_ENTER_VIEW";
export const NOTES_MENU_EXIT_VIEW = "NOTES_MENU_EXIT_VIEW";
export const NOTES_MENU_DELETE_NOTE = "NOTES_MENU_DELETE_NOTE";
export const NOTES_MENU_ADD_NOTE = "NOTES_MENU_ADD_NOTE";
export const NOTES_MENU_ENTER_EDIT = "NOTES_MENU_ENTER_EDIT";
export const NOTES_MENU_EXIT_EDIT = "NOTES_MENU_EXIT_EDIT";

// View Note
export const VIEW_NOTE_LOAD = "VIEW_NOTE_LOAD";
