// Notes Menu
const ENTER_CREATE_NOTE = "ENTER_CRETE_NOTE";
const CLOSE_CREATE_NOTE = "CLOSE_CREATE_NOTE";
const NOTES_MENU_LOAD = "NOTES_MENU_LOAD";
const NOTES_MENU_ENTER_VIEW = "NOTES_MENU_ENTER_VIEW";
const NOTES_MENU_EXIT_VIEW = "NOTES_MENU_EXIT_VIEW";
const NOTES_MENU_DELETE_NOTE = "NOTES_MENU_DELETE_NOTE";
const NOTES_MENU_ADD_NOTE = "NOTES_MENU_ADD_NOTE";
const NOTES_MENU_ENTER_EDIT = "NOTES_MENU_ENTER_EDIT";

// Create Note
const CREATE_NOTE_ENTER_TITLE = "CREATE_NOTE_ENTER_TITLE";
const CREATE_NOTE_ENTER_DESCRIPTION = "CREATE_NOTE_ENTER_DESCRIPTION";
const CREATE_NOTE_ADD_COMMENT = "CREATE_NOTE_ADD_COMMENT";
const CREATE_NOTE_WRITE_COMMENT = "CREATE_NOTE_WRITE_COMMENT";
const CREATE_NOTE_ADD_TAG = "CREATE_NOTE_ADD_TAG";
const CREATE_NOTE_RESET = "CREATE_NOTE_RESET";
const CREATE_NOTE_DELETE_COMMENT = "CREATE_NOTE_DELETE_COMMENT";

// View Note
const VIEW_NOTE_LOAD = "VIEW_NOTE_LOAD";

// Edit Note
const EDIT_NOTE_LOAD = "EDIT_NOTE_LOAD";

export { 
  ENTER_CREATE_NOTE,
  CLOSE_CREATE_NOTE,
  NOTES_MENU_LOAD, 
  NOTES_MENU_ENTER_VIEW,
  NOTES_MENU_EXIT_VIEW,
  NOTES_MENU_DELETE_NOTE, 
  NOTES_MENU_ADD_NOTE,  
  NOTES_MENU_ENTER_EDIT,

  CREATE_NOTE_ENTER_TITLE,
  CREATE_NOTE_ENTER_DESCRIPTION,
  CREATE_NOTE_ADD_COMMENT,
  CREATE_NOTE_WRITE_COMMENT,
  CREATE_NOTE_ADD_TAG,
  CREATE_NOTE_RESET,
  CREATE_NOTE_DELETE_COMMENT,

  VIEW_NOTE_LOAD,

  EDIT_NOTE_LOAD
};
