export const VIEW_NOTE_ENTER = "VIEW_NOTE_ENTER";
export const VIEW_NOTE_EXIT = "EXIT";
export const VIEW_COLLECTION_ENTER = "VIEW_COLLECTION_ENTER";
export const VIEW_COLLECTION_EXIT = "VIEW_COLLECTION_EXIT";
export const START_LOADING_NOTE = "START_LOADING_NOTE_VIEW";
export const START_LOADING_COLLECTION = "START_LOADING_COLLECTION_VIEW";
export const END_LOADING_NOTE = "END_LOADING_NOTE_VIEW";
export const END_LOADING_COLLECTION = "END_LOADING_COLLECTION_VIEW";