const START_FETCH = 'NOTES/VIEW/START_FETCH';
const END_FETCH = 'NOTES/VIEW/END_FETCH';
const LOAD_NOTE = 'NOTES/VIEW/LOAD_NOTE';
const RESET = 'NOTES/VIEW/RESET';

export default {
  START_FETCH,
  END_FETCH,
  LOAD_NOTE,
  RESET
};
