const START_FETCH = 'COLLECTIONS/VIEW/START_FETCH';
const END_FETCH = 'COLLECTIONS/VIW/END_FETCH';
const LOAD_COLLECTION = 'COLLECTIONS/VIEW/LOAD_COLLECTION';
const RESET = 'COLLECTIONS/VIEW/RESET';

export default {
  START_FETCH,
  END_FETCH,
  LOAD_COLLECTION,
  RESET
};
